apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: {{ .Values.app.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
#  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.bePort1 }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.bePort1 }}
  - name: https
    port: {{ .Values.service.bePort2 }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.bePort2 }}
#    nodePort: {{ .Values.service.nodePort }}
  - name: swagger
    port: {{ .Values.service.swaggerPort }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.swaggerPort }}

