apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: {{ .Values.app.mariaDbName }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.app.mariaDbName }}
  ports:
  - port: {{ .Values.service.mariaPort }}
    protocol: {{ .Values.service.protocol }}
